/* generated by pull.js */
import _js from "./userscript.js";
import _css from "!css-loader!./userstyle.css";
import _css2 from "!css-loader!./hide-labels.css";
import _asset from "!url-loader!./close.svg";
export const resources = {
  "userscript.js": _js,
  "userstyle.css": _css,
  "hide-labels.css": _css2,
  "close.svg": _asset,
};
